export const beFrMarket = {
  key: 'BE-FR',
  directPostContinueFlow: true,
  baseUrl: 'https://vasco-translator.be/fr/',
  checkoutPath: 'commande',
  product: {
    name: 'Vasco Translator Q1',
    path: '/fr/traducteurs/vasco-translator-q1',
  },
  labels: {
    cart: /Panier/i,
    addToCart: /Ajouter au panier/i,
    continue: /Continuer/i,
    // The BE-FR checkout currently renders the summary's accessible name in English.
    summary: /Summary|Sommaire|Récapitulatif|Résumé|Podsumowanie/i,
    personalInfoStep: /Informations personnelles|Vos informations|Informacje osobiste/i,
    addressesStep: /^Adresses$/i,
    addressReady: /Quelle est votre adresse de facturation\?/i,
    shippingStep: /Mode de livraison|Méthode de livraison|Livraison/i,
    shippingReady: /Choisissez votre mode de livraison/i,
    paymentReady: /Comment souhaitez-vous payer|Paiement/i,
    companyCustomer: /^Entreprise$/i,
    individualCustomer: /Client individuel|Particulier/i,
    firstName: /^Prénom|^Prenom/i,
    lastName: /^Nom/i,
    email: /E-mail|Email/i,
    phone: /Téléphone|Telephone/i,
    terms: /Conditions générales|Conditions d'utilisation|Warunki korzystania/i,
    privacy: /Politique de confidentialité|Politykę prywatności|Polityke prywatnosci/i,
    loadingInfo: /Nous vérifions vos données|Vérification de vos données|Sprawdzamy Twoje dane/i,
    viesSuccess: /Numéro de TVA .* vérifié|Numéro TVA .* vérifié|został zweryfikowany pomyślnie/i,
  },
  placeholders: {
    firstName: /prénom|imię/i,
    lastName: /nom|nazwisko/i,
    company: /société|societe|entreprise|firma/i,
    taxId: /tva|vat|nip|numéro/i,
    address1: /^enter adresse$|^adresse$/i,
    address2: /complément d'adresse|uzupełnienie/i,
    postcode: /code postal|kod pocztowy/i,
    city: /^enter ville$|^ville$/i,
  },
  placeholderHints: {
    address: 'adresse',
    postcode: 'postal',
  },
  pricePatterns: {
    subtotal: /Sous-total\s*([\d\s.,]+)\s*(?:zł|€|EUR)?/i,
    shipping: /Livraison\s*([\d\s.,]+)\s*(?:zł|€|EUR)?/i,
    tax: /TVA(?:\s*\(incluse\))?\s*([\d\s.,]+)\s*(?:zł|€|EUR)?/i,
    total: /(?:TOTAL|Total)\s*:?\s*([\d\s.,]+)\s*(?:zł|€|EUR)?/i,
  },
  summaryPatterns: {
    total: /(?:TOTAL|Total|Mode de livraison|Livraison)/i,
  },
  timeouts: {
    positiveVies: 45000,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Zamknij"]',
      'button[aria-label="Close"]',
      'button[aria-label="Fermer"]',
      'button[title="Close"]',
      'button[title="Fermer"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|inscri/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Close"], #newsletter_popup button[aria-label="Fermer"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /fermer|close|plus tard|skip/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-BE-to-PT',
      description: 'client individuel dans l’UE garde le sous-total sans changement',
      billingCountry: 'Portugal',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisbonne',
        phone: '123456789',
      },
    },
    {
      key: 'company-BE-to-PT-no-vies',
      description: 'entreprise avec format TVA correct mais absente de VIES garde le sous-total sans changement',
      billingCountry: 'Portugal',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Entreprise test sans VIES',
        taxId: '500100145',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisbonne',
        phone: '123456789',
      },
    },
    {
      key: 'BE-to-FR',
      description: 'entreprise avec numéro VIES valide dans un autre pays UE enlève la TVA',
      billingCountry: 'France',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Entreprise test VIES FR',
        taxId: '59542051180',
        address1: '10 Rue de la Paix',
        address2: '',
        postcode: '75002',
        city: 'Paris',
        phone: '123456789',
      },
    },
  ],
};
