export const bgMarket = {
  key: 'BG',
  directPostContinueFlow: true,
  baseUrl: 'https://vasco-electronics.bg/',
  checkoutPath: 'poracka',
  product: {
    name: 'Vasco Translator Q1',
    path: '/translator/vasco-translator-q1',
  },
  labels: {
    cart: /Количка/i,
    addToCart: /Добави в кошницата/i,
    continue: /Продължи|Продължете/i,
    summary: /Обобщение|Резюме|Подробности за поръчката/i,
    personalInfoStep: /Лична информация|Лични данни|Информация за клиента/i,
    addressesStep: /Адреси|Адрес/i,
    addressReady: /Какъв е вашият адрес за фактуриране\?/i,
    shippingStep: /Начин на доставка|Метод на доставка|Доставка/i,
    shippingReady: /Изберете вашия метод за доставка/i,
    paymentReady: /Как бихте искали да платите|Как искате да платите|Плащане/i,
    companyCustomer: /^Фирма$|^Компания$/i,
    individualCustomer: /Индивидуален клиент|Частно лице/i,
    firstName: /^Име/i,
    lastName: /^Фамилия|^Име на семейство/i,
    email: /E-mail|Имейл/i,
    phone: /Телефон/i,
    terms: /Условия(та)?/i,
    privacy: /Политика(та)? за поверителност/i,
    loadingInfo: /Проверяваме Вашите данни|Проверяваме данните Ви|Проверка на данните/i,
    viesSuccess: /Номер.*ДДС.*успешно|Номер.*ДДС.*потвърден|проверен успешно/i,
  },
  placeholders: {
    firstName: /(enter\s*)?име/i,
    lastName: /(enter\s*)?фамилия|(enter\s*)?име на семейство/i,
    company: /(enter\s*)?фирма|(enter\s*)?компания/i,
    taxId: /(enter\s*)?ддс|(enter\s*)?vat|(enter\s*)?номер/i,
    address1: /^въведете адрес$|^адрес$/i,
    address2: /допълнителен адрес|допълнение|address 2/i,
    postcode: /(enter\s*)?пощенски код/i,
    city: /(enter\s*)?град/i,
  },
  placeholderHints: {
    address: 'адрес',
    postcode: 'код',
  },
  pricePatterns: {
    subtotal: /Междинна сум(?:а)?\s*([\d\s.,]+)\s*(?:лв|€|EUR)?/i,
    shipping: /Доставка\s*([\d\s.,]+)\s*(?:лв|€|EUR)?/i,
    tax: /ДДС|VAT(?:\s*\(вкл\.\))?\s*([\d\s.,]+)\s*(?:лв|€|EUR)?/i,
    total: /Общо\s*([\d\s.,]+)\s*(?:лв|€|EUR)?/i,
  },
  summaryPatterns: {
    total: /Общо|Метод на доставка|Доставка/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Затвори"]',
      'button[aria-label="Затвори"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Затвори"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|бюлетин|абонира/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Затвори"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /затвори|close|не сега|skip/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-BG-to-DE',
      description: 'индивидуален клиент в ЕС запазва междинната сума без промяна',
      billingCountry: 'Германия',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Friedrichstrasse 123',
        address2: '',
        postcode: '10117',
        city: 'Berlin',
        phone: '123456789',
      },
    },
    {
      key: 'company-BG-to-DE-no-vies',
      description: 'фирма с валиден формат на ДДС номер, но без запис във VIES запазва междинната сума без промяна',
      billingCountry: 'Германия',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Тест фирма без VIES',
        taxId: '500100145',
        address1: 'Friedrichstrasse 123',
        address2: '',
        postcode: '10117',
        city: 'Berlin',
        phone: '123456789',
      },
    },
    {
      key: 'BG-to-DE',
      description: 'фирма с валиден VIES номер в друга държава от ЕС премахва ДДС',
      billingCountry: 'Германия',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Testfirma VIES DE',
        taxId: '129273398',
        address1: 'Friedrichstrasse 123',
        address2: '',
        postcode: '10117',
        city: 'Berlin',
        phone: '123456789',
      },
    },
  ],
};
