export const czMarket = {
  key: 'CZ',
  baseUrl: 'https://vasco-electronics.cz/',
  checkoutPath: 'objednavka',
  product: {
    name: 'Vasco Translator Q1',
    path: '/translator/vasco-translator-q1',
  },
  labels: {
    cart: /Košík/i,
    addToCart: /Přidat do košíku/i,
    continue: /Pokračovat/i,
    summary: /Shrnutí|Souhrn objednávky/i,
    personalInfoStep: /Osobní údaje|Osobní informace/i,
    addressesStep: /Adresy|Adresa/i,
    addressReady: /Jaká je vaše fakturační adresa\?/i,
    shippingStep: /Způsob dopravy|Doprava/i,
    companyCustomer: /^Firma$/i,
    individualCustomer: /Soukromá osoba|Individuální zákazník/i,
    firstName: /^Jméno|^Křestní jméno/i,
    lastName: /^Příjmení/i,
    email: /E-mail/i,
    phone: /Telefon/i,
    terms: /Přečetl\/a jsem si a souhlasím s podmínkami|podmínkami/i,
    privacy: /Přečetl\/a jsem a souhlasím se Zásadami ochrany osobních údajů|Zásady ochrany osobních údajů|Ochrana osobních údajů/i,
    loadingInfo: /Ověřujeme vaše údaje|Kontrolujeme vaše údaje/i,
    viesSuccess: /DIČ.*úspěšně ověřeno|DIČ.*ověřeno/i,
  },
  placeholders: {
    firstName: /jméno|křestní jméno/i,
    lastName: /příjmení/i,
    company: /firma|společnost/i,
    taxId: /dič|vat|daň/i,
    address1: /ulice/i,
    address2: /číslo popisné/i,
    postcode: /psč|poštovní směrovací číslo/i,
    city: /město\s*\/\s*obec|město/i,
  },
  placeholderHints: {
    address: 'adresa',
    postcode: 'psč',
  },
  pricePatterns: {
    subtotal: /Mezisoučet\s*([\d\s.,]+)\s*(?:Kč|€|EUR)?/i,
    shipping: /Doprava\s*([\d\s.,]+)\s*(?:Kč|€|EUR)?/i,
    tax: /DPH|VAT(?:\s*\(včetně\))?\s*([\d\s.,]+)\s*(?:Kč|€|EUR)?/i,
    total: /Celkem\s*([\d\s.,]+)\s*(?:Kč|€|EUR)?/i,
  },
  summaryPatterns: {
    total: /Celkem|Způsob dopravy|Doprava/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Zavřít"]',
      'button[aria-label="Zavřít"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Zavřít"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|odběr|přihlásit/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Zavřít"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /zavřít|close|později|skip/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-CZ-to-DE',
      description: 'individuální zákazník v EU ponechá mezisoučet beze změny',
      billingCountry: 'Německo',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Friedrichstrasse',
        address2: '123',
        postcode: '10117',
        city: 'Berlin',
        phone: '123456789',
      },
    },
    {
      key: 'company-CZ-to-DE-no-vies',
      description: 'firma s platným formátem DIČ, ale bez záznamu ve VIES ponechá mezisoučet beze změny',
      billingCountry: 'Německo',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Test firma bez VIES',
        taxId: '500100145',
        address1: 'Friedrichstrasse',
        address2: '123',
        postcode: '10117',
        city: 'Berlin',
        phone: '123456789',
      },
    },
    {
      key: 'CZ-to-DE',
      description: 'firma s platným VIES číslem v jiné zemi EU odstraní DPH',
      billingCountry: 'Německo',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Testfirma VIES DE',
        taxId: '129273398',
        address1: 'Friedrichstrasse',
        address2: '123',
        postcode: '10117',
        city: 'Berlin',
        phone: '123456789',
      },
    },
  ],
};
