export const dkMarket = {
  key: 'DK',
  baseUrl: 'https://vasco-translator.dk/',
  checkoutPath: 'ordre',
  repeatPersonalContinueClick: true,
  product: {
    name: 'Vasco Translator Q1',
    path: '/oversaettere/vasco-translator-q1',
  },
  timeouts: {
    continueFromPersonalInformation: 45000,
  },
  labels: {
    cart: /Kurv|Indkøbskurv/i,
    addToCart: /Læg i kurv|Tilføj til kurv/i,
    continue: /Fortsæt|Videre/i,
    summary: /Oversigt|Ordreoversigt|Opsummering/i,
    personalInfoStep: /Personlige oplysninger|Dine oplysninger/i,
    addressesStep: /^Adresser$/i,
    addressReady: /Hvad er din faktureringsadresse\?/i,
    shippingStep: /Leveringsmetode|Fragtmetode|Levering/i,
    companyCustomer: /^Virksomhed$|^Firma$/i,
    individualCustomer: /Enkeltperson|Privatkunde|Privatperson/i,
    firstName: /^Fornavn/i,
    lastName: /^Efternavn|^Navn/i,
    email: /Mailadresse|E-mail/i,
    phone: /Mobiltelefon|Telefon/i,
    terms: /servicevilkår|servicevilkårene|vilkår og betingelser|betingelser/i,
    privacy: /privatlivspolitik|privatlivspolitikken|persondatapolitik/i,
    loadingInfo: /Vi kontrollerer dine oplysninger|Vi verificerer dine oplysninger/i,
    viesSuccess: /momsnummer.*bekræftet|moms.*verificeret|gyldigt momsnummer/i,
  },
  placeholders: {
    firstName: /fornavn/i,
    lastName: /efternavn|navn/i,
    company: /firma|virksomhed/i,
    taxId: /moms|vat|cvr/i,
    address1: /^indtast adresse$|^adresse$/i,
    address2: /adressekomplement|adresse 2|yderligere adresse|husnr/i,
    postcode: /postnummer/i,
    city: /by/i,
  },
  placeholderHints: {
    address: 'adresse',
    postcode: 'post',
  },
  pricePatterns: {
    subtotal: /(?:Subtotal|Delsum)\s*([\d\s.,]+)\s*(?:kr\.?|DKK|€|EUR)?/i,
    shipping: /(?:Levering|Fragt)\s*([\d\s.,]+)\s*(?:kr\.?|DKK|€|EUR)?/i,
    tax: /Moms|VAT(?:\s*\(inkl\.\))?\s*([\d\s.,]+)\s*(?:kr\.?|DKK|€|EUR)?/i,
    total: /I alt\s*([\d\s.,]+)\s*(?:kr\.?|DKK|€|EUR)?/i,
  },
  summaryPatterns: {
    total: /I alt|Leveringsmetode|Fragt|Levering/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Luk"]',
      'button[aria-label="Luk"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Luk"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|tilmeld|abonn/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Luk"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /luk|close|senere|skip/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-DK-to-PT',
      description: 'privatkunde i EU beholder delsummen uændret',
      billingCountry: 'Portugal',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Rua do Comercio',
        address2: '123',
        postcode: '1100-150',
        city: 'Lissabon',
        phone: '123456789',
      },
    },
    {
      key: 'company-DK-to-PT-no-vies',
      description: 'firma med korrekt momsnummerformat, men uden VIES-match beholder delsummen uændret',
      billingCountry: 'Portugal',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Testfirma uden VIES',
        taxId: '500100145',
        address1: 'Rua do Comercio',
        address2: '123',
        postcode: '1100-150',
        city: 'Lissabon',
        phone: '123456789',
      },
    },
    {
      key: 'DK-to-PT',
      description: 'firma med gyldigt VIES-nummer i et andet EU-land fjerner moms',
      billingCountry: 'Portugal',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Testfirma VIES PT',
        taxId: '500100144',
        address1: 'Rua do Comercio',
        address2: '123',
        postcode: '1100-150',
        city: 'Lissabon',
        phone: '123456789',
      },
    },
  ],
};
