export const esMarket = {
  key: 'ES',
  forceValidationWait: true,
  skipCountryReadyCheck: true,
  debugLikeContinueFlow: true,
  waitForAddressSubmitButtonAfterContinue: true,
  webkitDebugContinueFlow: true,
  webkitContinueFlow: true,
  domFirstContinueClick: true,
  reloadCheckoutAfterContinue: true,
  forceAddressStepAfterContinue: true,
  addressStepUrl: '/pedido?id_address=0',
  personalContinueSelector: 'button[name="continue"][data-link-action="register-new-customer"]',
  addressReadySelectors: ['button[name="confirm-addresses"]'],
  addressSubmitSelector: 'button[name="confirm-addresses"]',
  returnAfterContinueClick: true,
  stepVisibleValidation: true,
  timeouts: {
    continueFromPersonalInformation: 90000,
    preContinueWait: 1500,
    postContinueWait: 3000,
    viesValidation: 40000,
  },
  baseUrl: 'https://traductor-de-voz.es/',
  checkoutPath: 'pedido',
  product: {
    name: 'Traductor Q1',
    path: '/traductor/vasco-translator-q1',
  },
  labels: {
    cart: /Cesta de la compra|Carrito|Cesta/i,
    addToCart: /Añadir a la cesta|Añadir al carrito|Agregar al carrito/i,
    continue: /Continuar/i,
    summary: /Resumen|Resumen del pedido/i,
    personalInfoStep: /Datos Personales|Información personal|Tus datos/i,
    addressesStep: /^Direcciones$/i,
    addressReady: /dirección de facturación|¿Cuál es su dirección de facturación\?|¿Cuál es tu dirección de facturación\?|Elige si deseas la factura como Particular o Empresa\/Autónomo/i,
    shippingStep: /Método de envío|Entrega|Envío/i,
    shippingReady: /Elige el método de envío|Si deseas añadir un comentario sobre tu pedido/i,
    paymentReady: /¿Cómo te gustaría pagar\?|Estos datos se utilizarán para el pago/i,
    companyCustomer: /^Empresa\/Autónomo$|^Empresa$/i,
    individualCustomer: /^Persona$|^Cliente individual$|^Particular$/i,
    firstName: /^Nombre/i,
    lastName: /^Apellido|^Apellidos/i,
    email: /Dirección de correo electrónico|Correo electrónico|Email|E-mail/i,
    phone: /Teléfono/i,
    terms: /Términos de Servicio|Términos y condiciones|Condiciones generales|condiciones/i,
    privacy: /Política de Privacidad|Política de privacidad|privacidad/i,
    loadingInfo: /Estamos verificando tus datos|Verificando tus datos/i,
    viesSuccess: /NIF-IVA .* verificado|IVA .* verificado|ha sido verificado correctamente/i,
  },
  placeholders: {
    firstName: /nombre/i,
    lastName: /apellido|apellidos/i,
    company: /empresa/i,
    taxId: /nif|iva|vat|cif/i,
    address1: /^escribe dirección$|^dirección$/i,
    address2: /dirección complementaria|complementaria|complemento|dirección 2|adicional/i,
    postcode: /código postal|cp/i,
    city: /ciudad|localidad/i,
  },
  placeholderHints: {
    address: 'dirección',
    postcode: 'postal',
  },
  pricePatterns: {
    itemPrice: /Phantom Black\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    subtotal: /Subtotal\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    shipping: /Envío\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    tax: /IVA(?:\s*\(incluido\))?\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    total: /Total\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
  },
  summaryPatterns: {
    total: /Total|Método de envío|Envío/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Cerrar"]',
      'button[aria-label="Cerrar"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Cerrar"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|suscr/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Cerrar"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /cerrar|close|más tarde|skip/i }).first(),
    ],
  },
  timeouts: {
    positiveVies: 45000,
  },
  scenarios: [
    {
      key: 'individual-ES-to-DE',
      description: 'cliente particular de la UE mantiene el subtotal sin cambios',
      billingCountry: 'Alemania',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Friedrichstrasse',
        address2: '128',
        postcode: '10117',
        city: 'Berlín',
        phone: '123456789',
      },
    },
    {
      key: 'company-ES-to-DE-no-vies',
      description: 'empresa con formato IVA correcto, pero sin entrada en VIES mantiene el subtotal sin cambios',
      billingCountry: 'Alemania',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Empresa test sin VIES',
        taxId: '129273399',
        address1: 'Friedrichstrasse',
        address2: '128',
        postcode: '10117',
        city: 'Berlín',
        phone: '123456789',
      },
    },
    {
      key: 'company-ES-to-PT-vies-no-change',
      description: 'empresa con número VIES válido en otro país de la UE mantiene el subtotal sin cambios en el mercado ES',
      billingCountry: 'Portugal',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Empresa test VIES PT',
        taxId: '500100144',
        address1: 'Rua do Comercio',
        address2: '128',
        postcode: '1100-150',
        city: 'Lisboa',
        phone: '123456789',
      },
    },
  ],
};
