export const fiMarket = {
  key: 'FI',
  baseUrl: 'https://vasco-translator.fi/',
  checkoutPath: 'tilaus',
  product: {
    name: 'Vasco Translator Q1',
    path: '/kaantajat/vasco-translator-q1',
  },
  labels: {
    cart: /Ostoskori/i,
    addToCart: /Lisää ostoskoriin|Lisää koriin/i,
    continue: /Jatka/i,
    summary: /Yhteenveto|Tilauksen yhteenveto/i,
    personalInfoStep: /Henkilötiedot|Omat tiedot/i,
    addressesStep: /Osoitteet|Osoite/i,
    shippingStep: /Toimitustapa|Toimitus/i,
    companyCustomer: /^Yrityksenä$|^Yritys$/i,
    individualCustomer: /Henkilöasiakkaana|Yksityishenkilö|Yksityinen asiakas/i,
    firstName: /^Etunimi/i,
    lastName: /^Sukunimi|^Nimi/i,
    email: /Sähköposti|E-mail/i,
    phone: /Matkapuhelin|Puhelin/i,
    terms: /palveluehdot|ehdot ja edellytykset|ehdot/i,
    privacy: /tietosuojakäytäntö|tietosuojaseloste|tietosuoja/i,
    loadingInfo: /Tarkistamme tietojasi|Vahvistamme tietojasi/i,
    viesSuccess: /ALV-numero.*vahvistettu|ALV.*vahvistettu|voimassa oleva ALV-numero/i,
  },
  placeholders: {
    firstName: /etunimi/i,
    lastName: /sukunimi|nimi/i,
    company: /yritys|yrityksen nimi/i,
    taxId: /alv|vat|y-tunnus/i,
    address1: /^anna osoite$|^osoite$/i,
    address2: /osoitteen lisärivi|lisärivi|osoite 2|lisäosoite|huoneisto/i,
    postcode: /postinumero/i,
    city: /postitoimipaikka|kaupunki/i,
  },
  placeholderHints: {
    address: 'osoite',
    postcode: 'posti',
  },
  pricePatterns: {
    subtotal: /(?:Välisumma|Subtotal)\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    shipping: /(?:Toimitus|Rahti)\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    tax: /ALV|VAT(?:\s*\(sis\.\))?\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    total: /Yhteensä\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
  },
  summaryPatterns: {
    total: /Yhteensä|Toimitustapa|Toimitus/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Sulje"]',
      'button[aria-label="Sulje"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Sulje"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|uutiskirje|tilaa/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Sulje"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /sulje|close|myöhemmin|skip/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-FI-to-PT',
      description: 'yksityisasiakas EU:ssa pitää välisumman ennallaan',
      billingCountry: 'Portugali',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Rua do Comercio',
        address2: '123',
        postcode: '1100-150',
        city: 'Lissabon',
        phone: '123456789',
      },
    },
    {
      key: 'company-FI-to-PT-no-vies',
      description: 'yritys oikeassa ALV-muodossa ilman VIES-osumaa pitää välisumman ennallaan',
      billingCountry: 'Portugali',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Testiyritys ilman VIES',
        taxId: '500100145',
        address1: 'Rua do Comercio',
        address2: '123',
        postcode: '1100-150',
        city: 'Lissabon',
        phone: '123456789',
      },
    },
    {
      key: 'FI-to-PT',
      description: 'yritys voimassa olevalla VIES-numerolla toisessa EU-maassa poistaa ALV:n',
      billingCountry: 'Portugali',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Testiyritys VIES PT',
        taxId: '500100144',
        address1: 'Rua do Comercio',
        address2: '123',
        postcode: '1100-150',
        city: 'Lissabon',
        phone: '123456789',
      },
    },
  ],
};
