export const frMarket = {
  key: 'FR',
  baseUrl: 'https://vasco-electronics.fr/',
  checkoutPath: 'commande',
  product: {
    name: 'Vasco Translator Q1',
    path: '/traducteurs/vasco-translator-q1',
  },
  labels: {
    cart: /Panier/i,
    addToCart: /Ajouter au panier/i,
    continue: /Poursuivre|Continuer/i,
    summary: /Sommaire|Récapitulatif|Résumé/i,
    personalInfoStep: /Informations personnelles|Vos informations/i,
    addressesStep: /Adresses|Adresse/i,
    shippingStep: /Mode de livraison|Méthode de livraison|Livraison/i,
    companyCustomer: /^Entreprise$/i,
    individualCustomer: /Individuel|Client individuel|Particulier/i,
    firstName: /^Prénom|^Prenom/i,
    lastName: /^Nom/i,
    email: /E-mail|Email/i,
    phone: /Téléphone|Telephone/i,
    terms: /Conditions générales|Conditions d'utilisation/i,
    privacy: /Politique de confidentialité/i,
    loadingInfo: /Nous vérifions vos données|Vérification de vos données/i,
    viesSuccess: /Numéro de TVA .* vérifié|Numéro TVA .* vérifié/i,
  },
  placeholders: {
    firstName: /prénom/i,
    lastName: /nom/i,
    company: /société|societe|entreprise/i,
    taxId: /tva|vat|numéro/i,
    address1: /^saisir le adresse$|^adresse$/i,
    address2: /complément d'adresse/i,
    postcode: /code postal/i,
    city: /^saisir le ville$|^ville$/i,
  },
  placeholderHints: {
    address: 'adresse',
    postcode: 'postal',
  },
  pricePatterns: {
    subtotal: /Sous-total\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    shipping: /Livraison\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    tax: /TVA(?:\s*\(incluse\))?\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    total: /(?:TOTAL|Total)\s*:?\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
  },
  summaryPatterns: {
    total: /(?:TOTAL|Total|Mode de livraison|Livraison)/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Fermer"]',
      'button[aria-label="Fermer"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Fermer"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|inscri/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Close"], #newsletter_popup button[aria-label="Fermer"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /fermer|close|plus tard|skip/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-FR-to-PT',
      description: 'client individuel dans l’UE garde le sous-total sans changement',
      billingCountry: 'Portugal',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisbonne',
        phone: '123456789',
      },
    },
    {
      key: 'company-FR-to-PT-no-vies',
      description: 'entreprise avec format TVA correct mais absente de VIES garde le sous-total sans changement',
      billingCountry: 'Portugal',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Entreprise test sans VIES',
        taxId: '500100145',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisbonne',
        phone: '123456789',
      },
    },
    {
      key: 'FR-to-PT',
      description: 'entreprise avec numéro VIES valide dans un autre pays UE enlève la TVA',
      billingCountry: 'Portugal',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Entreprise test VIES PT',
        taxId: '500100144',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisbonne',
        phone: '123456789',
      },
    },
  ],
};
