export const hrMarket = {
  key: 'HR',
  baseUrl: 'https://vasco-translator.hr/',
  checkoutPath: 'narudzba',
  product: {
    name: 'Vasco Translator Q1',
    path: '/translator/vasco-translator-q1',
  },
  labels: {
    cart: /Košarica|Košaricu/i,
    addToCart: /Dodaj u košaricu/i,
    continue: /Nastavi|Nastavite/i,
    summary: /Sažetak|SAŽETAK|Pregled narudžbe/i,
    personalInfoStep: /Osobni podaci|Osobne informacije/i,
    addressesStep: /Adrese|Adresa/i,
    shippingStep: /Način dostave|Dostava/i,
    companyCustomer: /^Tvrtka$/i,
    individualCustomer: /Privatni kupac|Fizička osoba|Individualni kupac/i,
    firstName: /^Ime/i,
    lastName: /^Prezime/i,
    email: /E-mail|Email/i,
    phone: /Telefon/i,
    terms: /Uvjete pružanja usluge|Uvjeti pružanja usluge|Uvjeti/i,
    privacy: /Pravila o privatnosti|Pravila privatnosti|Politika privatnosti/i,
    loadingInfo: /Provjeravamo vaše podatke|Provjera podataka/i,
    viesSuccess: /PDV.*uspješno|broj.*PDV.*potvrđen|uspješno provjeren/i,
  },
  placeholders: {
    firstName: /ime/i,
    lastName: /prezime/i,
    company: /tvrtka|kompanija|poduzeće/i,
    taxId: /oib|pdv|vat|porez/i,
    address1: /adresa|ulica/i,
    address2: /dodatna adresa|adresa 2|apartman|kat/i,
    postcode: /poštanski broj|poštanski|zip/i,
    city: /grad|mjesto/i,
  },
  placeholderHints: {
    address: 'adresa',
    postcode: 'pošt',
  },
  pricePatterns: {
    subtotal: /Međuzbroj\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    shipping: /Dostava\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    tax: /PDV|VAT(?:\s*\(uključen\))?\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    total: /Ukupno\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
  },
  summaryPatterns: {
    total: /Ukupno|Način dostave|Dostava/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Zatvori"]',
      'button[aria-label="Zatvori"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Zatvori"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|novosti|pretplat/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Zatvori"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /zatvori|close|kasnije|skip/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-HR-to-DE',
      description: 'privatni kupac u EU zadržava međuzbroj bez promjene',
      billingCountry: 'Njemačka',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Friedrichstrasse 123',
        address2: '',
        postcode: '10117',
        city: 'Berlin',
        phone: '123456789',
      },
    },
    {
      key: 'company-HR-to-DE-no-vies',
      description: 'tvrtka s ispravnim formatom PDV broja, ali bez VIES zapisa zadržava međuzbroj bez promjene',
      billingCountry: 'Njemačka',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Test tvrtka bez VIES-a',
        taxId: '129273399',
        address1: 'Friedrichstrasse 123',
        address2: '',
        postcode: '10117',
        city: 'Berlin',
        phone: '123456789',
      },
    },
    {
      key: 'HR-to-DE',
      description: 'tvrtka s valjanim VIES brojem u drugoj državi EU uklanja PDV',
      billingCountry: 'Njemačka',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Test tvrtka VIES DE',
        taxId: '129273398',
        address1: 'Friedrichstrasse 123',
        address2: '',
        postcode: '10117',
        city: 'Berlin',
        phone: '123456789',
      },
    },
  ],
};
