export const huMarket = {
  key: 'HU',
  baseUrl: 'https://vasco-electronics.hu/',
  checkoutPath: 'rendeles',
  product: {
    name: 'Vasco Translator Q1',
    path: '/translator/vasco-translator-q1',
  },
  labels: {
    cart: /Kosár/i,
    addToCart: /Add a kosárhoz|Kosárba|Kosárba tesz/i,
    continue: /Folytatás|Tovább/i,
    summary: /Összegzés|Rendelés összegzése|ÖSSZEGZÉS/i,
    personalInfoStep: /Személyes adatok|Személyes információk/i,
    addressesStep: /Címek|Cím/i,
    shippingStep: /Szállítási mód|Szállítás/i,
    companyCustomer: /^Cég$/i,
    individualCustomer: /Magánszemély|Egyéni vásárló/i,
    firstName: /^Keresztnév|^Vezetéknév utáni név|^Név/i,
    lastName: /^Vezetéknév/i,
    email: /E-mail|Email/i,
    phone: /Telefon/i,
    terms: /Szolgáltatási feltételek|Általános szerződési feltételek|feltételek/i,
    privacy: /Adatvédelmi szabályzat|Adatvédelmi irányelvek|adatvédelem/i,
    loadingInfo: /Ellenőrizzük az adatait|Adatok ellenőrzése/i,
    viesSuccess: /ÁFA.*sikeresen|adószám.*ellenőrizve|sikeresen ellenőrizve/i,
  },
  placeholders: {
    firstName: /keresztnév|név/i,
    lastName: /vezetéknév/i,
    company: /cég|vállalat|vállalkozás/i,
    taxId: /adószám|áfa|vat/i,
    address1: /cím|utca/i,
    address2: /cím 2|emelet|ajtó|kiegészítő cím/i,
    postcode: /irányítószám|postai/i,
    city: /város|település/i,
  },
  placeholderHints: {
    address: 'cím',
    postcode: 'irány',
  },
  pricePatterns: {
    subtotal: /Részösszeg\s*([\d\s.,]+)\s*(?:Ft|€|EUR)?/i,
    shipping: /Szállítás\s*([\d\s.,]+)\s*(?:Ft|€|EUR)?/i,
    tax: /ÁFA|VAT(?:\s*\(tartalmazza\))?\s*([\d\s.,]+)\s*(?:Ft|€|EUR)?/i,
    total: /Összesen\s*([\d\s.,]+)\s*(?:Ft|€|EUR)?/i,
  },
  summaryPatterns: {
    total: /Összesen|Szállítási mód|Szállítás/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Bezárás"]',
      'button[aria-label="Bezárás"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Bezárás"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|hírlevél|feliratkoz/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Bezárás"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /bezárás|close|később|skip/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-HU-to-DE',
      description: 'magánszemély az EU-ban változatlanul hagyja a részösszeget',
      billingCountry: 'Németország',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Friedrichstrasse 123',
        address2: '',
        postcode: '10117',
        city: 'Berlin',
        phone: '123456789',
      },
    },
    {
      key: 'company-HU-to-DE-no-vies',
      description: 'a helyes adószámformátumú, de VIES-bejegyzés nélküli cég változatlanul hagyja a részösszeget',
      billingCountry: 'Németország',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Teszt cég VIES nélkül',
        taxId: '129273399',
        address1: 'Friedrichstrasse 123',
        address2: '',
        postcode: '10117',
        city: 'Berlin',
        phone: '123456789',
      },
    },
    {
      key: 'HU-to-DE',
      description: 'egy másik EU-ország érvényes VIES-számával rendelkező cég eltávolítja az ÁFÁ-t',
      billingCountry: 'Németország',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Teszt cég VIES DE',
        taxId: '129273398',
        address1: 'Friedrichstrasse 123',
        address2: '',
        postcode: '10117',
        city: 'Berlin',
        phone: '123456789',
      },
    },
  ],
};
