export const itMarket = {
  key: 'IT',
  baseUrl: 'https://vasco-electronics.it/',
  checkoutPath: 'ordine',
  product: {
    name: 'Vasco Translator Q1',
    path: '/translator/vasco-translator-q1',
  },
  labels: {
    cart: /Carrello/i,
    addToCart: /Aggiungi al carrello/i,
    continue: /Continua/i,
    summary: /Riepilogo|Sommario ordine|RIEPILOGO/i,
    personalInfoStep: /Informazioni personali|Dati personali/i,
    addressesStep: /Indirizzi|Indirizzo/i,
    shippingStep: /Metodo di spedizione|Spedizione/i,
    shippingReady: /Scegli il tuo metodo di spedizione/i,
    paymentReady: /Come desideri pagare\?/i,
    companyCustomer: /^Azienda$/i,
    individualCustomer: /Cliente individuale|Privato|Persona fisica/i,
    firstName: /^Nome/i,
    lastName: /^Cognome/i,
    email: /E-mail|Email/i,
    phone: /Telefono/i,
    terms: /Termini di servizio|Termini e condizioni|condizioni/i,
    privacy: /Informativa sulla privacy|Privacy policy|privacy/i,
    loadingInfo: /Stiamo verificando i tuoi dati|Verifica dei dati/i,
    viesSuccess: /Partita IVA .* verificata|IVA .* verificata|verificato con successo/i,
  },
  placeholders: {
    firstName: /nome/i,
    lastName: /cognome/i,
    company: /azienda|impresa|società|societa/i,
    taxId: /partita iva|iva|vat|codice fiscale/i,
    address1: /^inserisci indirizzo$|^indirizzo$/i,
    address2: /complemento indirizzo|indirizzo 2|interno|scala|complementare/i,
    postcode: /cap|codice postale/i,
    city: /città|citta|comune/i,
  },
  placeholderHints: {
    address: 'indir',
    postcode: 'cap',
  },
  optionalSelects: [
    {
      extraVisible: true,
    },
  ],
  pricePatterns: {
    subtotal: /(?:Subtotale|Importo dell'ordine)\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    shipping: /Spedizione\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    tax: /IVA(?:\s*\(inclusa\))?\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    total: /Totale\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
  },
  summaryPatterns: {
    total: /Totale|Metodo di spedizione|Spedizione/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Chiudi"]',
      'button[aria-label="Chiudi"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Chiudi"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|iscriviti|abbon/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Chiudi"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /chiudi|close|più tardi|skip/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-IT-to-PT',
      description: 'il cliente privato nell’UE lascia il subtotale invariato',
      billingCountry: 'Portogallo',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisbona',
        phone: '123456789',
      },
    },
    {
      key: 'company-IT-to-PT-no-vies',
      description: 'l’azienda con formato IVA corretto ma senza voce VIES lascia il subtotale invariato',
      billingCountry: 'Portogallo',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Azienda test senza VIES',
        taxId: '500100145',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisbona',
        phone: '123456789',
      },
    },
    {
      key: 'IT-to-PT',
      description: 'l’azienda con numero VIES valido in un altro paese UE rimuove l’IVA',
      billingCountry: 'Portogallo',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Azienda test VIES PT',
        taxId: '500100144',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisbona',
        phone: '123456789',
      },
    },
  ],
};
