export const ltMarket = {
  key: 'LT',
  baseUrl: 'https://vasco-translator.lt/',
  checkoutPath: 'commande',
  product: {
    name: 'Vasco Translator Q1',
    path: '/vertimo-jrenginiai/vasco-translator-q1',
  },
  labels: {
    cart: /Pirkinių krepšelis|Krepšelis/i,
    addToCart: /Į krepšelį|Pridėti į krepšelį/i,
    continue: /Tęsti/i,
    summary: /Apibendrinimas|Užsakymo apibendrinimas|Santrauka/i,
    personalInfoStep: /Asmeninė informacija|Asmens duomenys/i,
    addressesStep: /Adresas|Adresai/i,
    shippingStep: /Pristatymo būdas|Pristatymas/i,
    companyCustomer: /^Įmonė$/i,
    individualCustomer: /Privatus klientas|Fizinis asmuo/i,
    firstName: /^Vardas/i,
    lastName: /^Pavardė/i,
    email: /E-mail|El\.?\s*paštas|Email/i,
    phone: /Telefonas/i,
    terms: /Perskaičiau ir susipažinau su sąlygomis|Paslaugų teikimo sąlygos|Naudojimo sąlygos|sąlygos/i,
    privacy: /Perskaičiau ir susipažinau su privatumo politika|Privatumo politika|Privatumo taisyklės|privatumo/i,
    loadingInfo: /Tikriname jūsų duomenis|Duomenų tikrinimas/i,
    viesSuccess: /PVM.*sėkmingai|PVM kodas.*patvirtintas|sėkmingai patikrintas/i,
  },
  placeholders: {
    firstName: /vardas/i,
    lastName: /pavardė/i,
    company: /įmonė|kompanija|bendrovė/i,
    taxId: /pvm|vat|mokesčių/i,
    address1: /adresas|gatvė/i,
    address2: /adresas 2|papildomas adresas|butas|aukštas/i,
    postcode: /pašto kodas|kodas/i,
    city: /miestas|vietovė/i,
  },
  placeholderHints: {
    address: 'adres',
    postcode: 'kodas',
  },
  pricePatterns: {
    subtotal: /Tarpinė suma\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    shipping: /Pristatymas\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    tax: /PVM(?:\s*\(įskaičiuotas\))?\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    total: /Iš viso\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
  },
  summaryPatterns: {
    total: /Iš viso|Pristatymo būdas|Pristatymas/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Uždaryti"]',
      'button[aria-label="Uždaryti"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Uždaryti"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|naujienlaišk|prenumer/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Uždaryti"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /uždaryti|close|vėliau|skip/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-LT-to-PT',
      description: 'privatus klientas ES palieka tarpinę sumą nepakitusią',
      billingCountry: 'Portugalija',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisabona',
        phone: '123456789',
      },
    },
    {
      key: 'company-LT-to-PT-no-vies',
      description: 'įmonė su teisingu PVM formato numeriu, bet be VIES įrašo palieka tarpinę sumą nepakitusią',
      billingCountry: 'Portugalija',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Test įmonė be VIES',
        taxId: '500100145',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisabona',
        phone: '123456789',
      },
    },
    {
      key: 'LT-to-PT',
      description: 'įmonė su galiojančiu VIES numeriu kitoje ES šalyje panaikina PVM',
      billingCountry: 'Portugalija',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Test įmonė VIES PT',
        taxId: '500100144',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisabona',
        phone: '123456789',
      },
    },
  ],
};
