export const nlMarket = {
  key: 'NL',
  baseUrl: 'https://vasco-electronics.nl/',
  checkoutPath: 'bestelling',
  product: {
    name: 'Vasco Translator Q1',
    path: '/vertalers/vasco-translator-q1',
  },
  labels: {
    cart: /Winkelwagen/i,
    addToCart: /In winkelwagen|Toevoegen aan winkelwagen/i,
    continue: /Verder|Doorgaan/i,
    summary: /Overzicht|Samenvatting|Besteloverzicht/i,
    personalInfoStep: /Persoonlijke gegevens|Persoonlijke informatie/i,
    addressesStep: /Adressen|Adres/i,
    shippingStep: /Verzendingswijze|Verzendmethode|Verzending/i,
    companyCustomer: /^Bedrijf$/i,
    individualCustomer: /Particulier|Privéklant|Individuele klant/i,
    firstName: /^Voornaam/i,
    lastName: /^Achternaam|^Naam/i,
    email: /E-mail|Email/i,
    phone: /Telefoon/i,
    terms: /Ik heb de Servicevoorwaarden gelezen en geaccepteerd|Servicevoorwaarden|algemene voorwaarden/i,
    privacy: /Ik heb het Privacybeleid gelezen en geaccepteerd|Privacybeleid|privacyverklaring|privacy/i,
    loadingInfo: /We controleren uw gegevens|Gegevens worden gecontroleerd/i,
    viesSuccess: /btw.*succesvol|btw-nummer.*geverifieerd|succesvol geverifieerd/i,
  },
  placeholders: {
    firstName: /voornaam/i,
    lastName: /achternaam|naam/i,
    company: /bedrijf|onderneming|firma/i,
    taxId: /btw|vat|belasting/i,
    address1: /^invoeren adres$|^adres$/i,
    address2: /toevoeging adres|adresregel 2|aanvulling/i,
    postcode: /postcode/i,
    city: /plaats|stad/i,
  },
  placeholderHints: {
    address: 'straat',
    postcode: 'postcode',
  },
  pricePatterns: {
    subtotal: /Subtotaal\s*(?:€\s*)?([\d\s.,]+)|Subtotaal\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    shipping: /Verzending\s*(?:€\s*)?([\d\s.,]+)|Verzending\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    tax: /inclusief BTW\s*(?:€\s*)?([\d\s.,]+)|BTW\s*(?:€\s*)?([\d\s.,]+)|BTW(?:\s*\(incl\.\))?\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    total: /Totaal\s*(?:€\s*)?([\d\s.,]+)|Totaal\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
  },
  summaryPatterns: {
    total: /Totaal|Verzendmethode|Verzending/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Sluiten"]',
      'button[aria-label="Sluiten"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Sluiten"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|aanmelden|abonneren/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Sluiten"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /sluiten|close|later|skip/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-NL-to-PT',
      description: 'particuliere klant in de EU laat het subtotaal ongewijzigd',
      billingCountry: 'Portugal',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Rua do Comercio',
        address2: '128',
        postcode: '1100-150',
        city: 'Lissabon',
        phone: '123456789',
      },
    },
    {
      key: 'company-NL-to-PT-no-vies',
      description: 'bedrijf met geldig btw-formaat maar zonder VIES-vermelding laat het subtotaal ongewijzigd',
      billingCountry: 'Portugal',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Testbedrijf zonder VIES',
        taxId: '500100145',
        address1: 'Rua do Comercio',
        address2: '128',
        postcode: '1100-150',
        city: 'Lissabon',
        phone: '123456789',
      },
    },
    {
      key: 'NL-to-PT',
      description: 'bedrijf met geldig VIES-nummer in een ander EU-land verwijdert de btw',
      billingCountry: 'Portugal',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Testbedrijf VIES PT',
        taxId: '500100144',
        address1: 'Rua do Comercio',
        address2: '128',
        postcode: '1100-150',
        city: 'Lissabon',
        phone: '123456789',
      },
    },
  ],
};
