export const plMarket = {
  key: 'PL',
  baseUrl: 'https://vasco-electronics.pl/',
  checkoutPath: 'zamowienie',
  redirectFallbackUrl: 'https://presta-pl.vasco-technologies.com/zamowienie',
  product: {
    name: 'Vasco Translator Q1',
    path: '/translator/vasco-translator-q1',
  },
  labels: {
    cart: /Koszyk/i,
    addToCart: /Dodaj do koszyka/i,
    continue: /Kontynuuj/i,
    summary: /Podsumowanie/i,
    personalInfoStep: /Informacje osobiste/i,
    addressesStep: /Adresy/i,
    shippingStep: /Metoda wysyłki/i,
    companyCustomer: /^Firma$/i,
    individualCustomer: /Indywidualny klient/i,
    firstName: /Imię|Imie/i,
    lastName: /Nazwisko/i,
    email: /E-mail/i,
    phone: /Telefon/i,
    terms: /Warunki korzystania z serwisu/i,
    privacy: /Politykę prywatności|Polityke prywatnosci/i,
    loadingInfo: /Sprawdzamy Twoje dane/i,
    viesSuccess: /Numer NIP został zweryfikowany pomyślnie/i,
  },
  placeholders: {
    firstName: /wprowadź imię/i,
    lastName: /wprowadź nazwisko/i,
    company: /wprowadź firm/i,
    taxId: /wprowadź numer nip/i,
    address1: /wprowadź adres$/i,
    address2: /wprowadź uzupełnienie adresu/i,
    postcode: /wprowadź kod pocztowy/i,
    city: /wprowadź miasto/i,
  },
  placeholderHints: {
    address: 'adres',
    postcode: 'kod',
  },
  pricePatterns: {
    subtotal: /Suma częściowa\s*([\d\s.,]+)\s*(?:zł|€|EUR)?/i,
    shipping: /Wysyłka\s*([\d\s.,]+)\s*(?:zł|€|EUR)?/i,
    tax: /VAT(?:\s*\(wliczony\))?\s*([\d\s.,]+)\s*(?:zł|€|EUR)?/i,
    total: /RAZEM:\s*([\d\s.,]+)\s*(?:zł|€|EUR)?/i,
  },
  summaryPatterns: {
    total: /Razem:|RAZEM:|Metoda wysyłki/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Zamknij"]',
      'button[aria-label="Zamknij"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Zamknij"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|zapisz się|zapisz sie|dołącz do newslettera|dolacz do newslettera/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Zamknij"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /zamknij|close|nie teraz|maybe later|skip/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-PL-to-PT',
      description: 'klient indywidualny w kraju UE zostawia sume czesciowa bez zmian',
      billingCountry: 'Portugalia',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisboa',
        phone: '123456789',
      },
    },
    {
      key: 'company-PL-to-PT-no-vies',
      description: 'firma z poprawnym formatem NIP, ale bez wpisu w VIES zostawia sume czesciowa bez zmian',
      billingCountry: 'Portugalia',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Firma testowa bez VIES',
        taxId: '500100145',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisboa',
        phone: '123456789',
      },
    },
    {
      key: 'PL-to-PT',
      description: 'firma z poprawnym numerem VIES w innym kraju UE usuwa VAT',
      billingCountry: 'Portugalia',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Firma testowa VIES PT',
        taxId: '500100144',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisboa',
        phone: '123456789',
      },
    },
  ],
};
