export const ptMarket = {
  key: 'PT',
  baseUrl: 'https://vasco-translator.pt/',
  checkoutPath: 'encomenda',
  product: {
    name: 'Vasco Translator Q1',
    path: '/tradutor/vasco-translator-q1',
  },
  labels: {
    cart: /Carrinho/i,
    addToCart: /Adicionar ao carrinho/i,
    continue: /Continuar/i,
    summary: /Resumo|Sumário/i,
    personalInfoStep: /Informações pessoais|Informação pessoal/i,
    addressesStep: /Endereços|Endereço/i,
    shippingStep: /Método de envio|Envio/i,
    shippingReady: /Escolha o seu método de envio/i,
    paymentReady: /Como deseja pagar\?/i,
    companyCustomer: /^Empresa$/i,
    individualCustomer: /Individual|Cliente individual|Particular/i,
    firstName: /^Nome/i,
    lastName: /^Apelido|^Sobrenome/i,
    email: /E-mail|Email/i,
    phone: /Telefone/i,
    terms: /Termos de Serviço|Termos e condições|condições/i,
    privacy: /Política de Privacidade|privacidade/i,
    loadingInfo: /Por favor, aguarde.*verificar os seus dados|Estamos a verificar os seus dados/i,
    viesSuccess: /NIF.*verificado|IVA.*verificado|verificado com sucesso/i,
  },
  placeholders: {
    firstName: /nome/i,
    lastName: /apelido|sobrenome/i,
    company: /empresa|companhia/i,
    taxId: /nif|iva|vat/i,
    address1: /^introduzir endereço$|^endereço$/i,
    address2: /complemento do endereço|morada 2|complemento|andar|porta/i,
    postcode: /código postal/i,
    city: /cidade|localidade/i,
  },
  placeholderHints: {
    address: 'endere',
    postcode: 'postal',
  },
  pricePatterns: {
    itemPrice: /Phantom Black\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    subtotal: /Subtotal\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    shipping: /Envio\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    tax: /Impostos incluídos|IVA(?:\s*\(incluído\))?\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    total: /Total\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
  },
  summaryPatterns: {
    total: /Total|Método de envio|Envio/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Fechar"]',
      'button[aria-label="Fechar"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Fechar"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|subscrever|subscri/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Fechar"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /fechar|close|mais tarde|skip/i }).first(),
    ],
  },
  timeouts: {
    viesValidation: 30000,
    positiveVies: 45000,
  },
  scenarios: [
    {
      key: 'individual-PT-to-DE',
      description: 'cliente particular na UE mantém o subtotal inalterado',
      billingCountry: 'Alemanha',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Friedrichstrasse 123',
        address2: '',
        postcode: '10117',
        city: 'Berlim',
        phone: '123456789',
      },
    },
    {
      key: 'company-PT-to-DE-no-vies',
      description: 'empresa com formato de IVA válido mas sem registo VIES mantém o subtotal inalterado',
      billingCountry: 'Alemanha',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Empresa teste sem VIES',
        taxId: '129273399',
        address1: 'Friedrichstrasse 123',
        address2: '',
        postcode: '10117',
        city: 'Berlim',
        phone: '123456789',
      },
    },
    {
      key: 'PT-to-DE',
      description: 'empresa com número VIES válido noutro país da UE remove o IVA',
      billingCountry: 'Alemanha',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Empresa teste VIES DE',
        taxId: '129273398',
        address1: 'Friedrichstrasse 123',
        address2: '',
        postcode: '10117',
        city: 'Berlim',
        phone: '123456789',
      },
    },
  ],
};
