export const roMarket = {
  key: 'RO',
  baseUrl: 'https://vasco-electronics.ro/',
  checkoutPath: 'comanda',
  product: {
    name: 'Vasco Translator Q1',
    path: '/translator/vasco-translator-q1',
  },
  labels: {
    cart: /Coș|Cos/i,
    addToCart: /Adaugă în coș|Adauga in cos/i,
    continue: /Continuă|Continua/i,
    summary: /Rezumat|Sumar|Sumarul comenzii|Total/i,
    personalInfoStep: /Date personale|Informații personale|Informatii personale/i,
    addressesStep: /Adrese|Adresă|Adresa/i,
    shippingStep: /Metoda de livrare|Livrare/i,
    shippingReady: /Alege metoda de livrare/i,
    companyCustomer: /^Firma$|^Companie$|Persoană juridică|Persoana juridica/i,
    individualCustomer: /Client individual|Persoană fizică|Persoana fizica|Individual/i,
    firstName: /Prenume/i,
    lastName: /^Nume/i,
    email: /E-mail|Email/i,
    phone: /Telefon/i,
    terms: /Termenii și condițiile|Termenii si conditiile|Termeni și condiții|Termeni si conditii/i,
    privacy: /Politica de confidențialitate|Politica de confidentialitate/i,
    loadingInfo: /Verificăm datele dvs|Verificam datele dvs/i,
    viesSuccess: /TVA.*verificat|număr.*TVA.*verificat|numar.*TVA.*verificat/i,
  },
  placeholders: {
    firstName: /prenume/i,
    lastName: /^nume/i,
    company: /firm|compani|societ/i,
    taxId: /cif|cui|tva|vat|cod fiscal/i,
    address1: /^adres[ăa]$|introduceți adresa|introduceti adresa|adres/i,
    address2: /completare adres|adresa 2|apartament|etaj/i,
    postcode: /cod poștal|cod postal|poștal|postal/i,
    city: /oraș|oras|localitate/i,
  },
  placeholderHints: {
    address: 'adres',
    postcode: 'cod',
  },
  optionalSelects: [
    {
      extraVisible: true,
    },
  ],
  pricePatterns: {
    subtotal: /Subtotal\s*([\d\s.,]+)\s*(?:lei|RON|€|EUR)?/i,
    shipping: /Livrare\s*([\d\s.,]+)\s*(?:lei|RON|€|EUR)?/i,
    tax: /(?:TVA|Taxele incluse)\s*([\d\s.,]+)\s*(?:lei|RON|€|EUR)?/i,
    total: /Total(?:\s*\(cu taxe\))?\s*([\d\s.,]+)\s*(?:lei|RON|€|EUR)?/i,
  },
  summaryPatterns: {
    total: /Total|Livrare|Metoda de livrare/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Închide"]',
      'button.close-dialog-icon[aria-label="Inchide"]',
      'button[aria-label="Închide"]',
      'button[aria-label="Inchide"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Închide"]',
      'button[title="Inchide"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|abon|noutăți|noutati/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Închide"], #newsletter_popup button[aria-label="Inchide"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /închide|inchide|close|mai târziu|mai tarziu|skip/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-RO-to-PT',
      description: 'clientul individual din UE lasă subtotalul neschimbat',
      billingCountry: 'Portugalia',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisboa',
        phone: '123456789',
      },
    },
    {
      key: 'company-RO-to-PT-no-vies',
      description: 'firma cu format TVA corect dar fără intrare VIES lasă subtotalul neschimbat',
      billingCountry: 'Portugalia',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Firma test fara VIES',
        taxId: '500100145',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisboa',
        phone: '123456789',
      },
    },
    {
      key: 'RO-to-PT',
      description: 'firma cu număr VIES valid într-o altă țară UE elimină TVA',
      billingCountry: 'Portugalia',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Firma test VIES PT',
        taxId: '500100144',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisboa',
        phone: '123456789',
      },
    },
  ],
};
