export const seMarket = {
  key: 'SE',
  baseUrl: 'https://vasco-translator.se/',
  checkoutPath: 'bestallning',
  product: {
    name: 'Vasco Translator Q1',
    path: '/oversattare/vasco-translator-q1',
  },
  labels: {
    cart: /Kundvagn|Varukorg/i,
    addToCart: /Lägg i kundvagnen|Lagg i kundvagnen|Lägg i varukorgen|Lagg i varukorgen/i,
    continue: /Fortsätt|Fortsatt|Gå vidare/i,
    summary: /Sammanfattning|Ordersammanfattning|Totalt/i,
    personalInfoStep: /Personuppgifter|Dina uppgifter|Personliga uppgifter/i,
    addressesStep: /Adresser|Adress/i,
    shippingStep: /Leveransmetod|Leveranssätt|Leverans/i,
    shippingReady: /Välj leveransmetod|Valj leveransmetod/i,
    companyCustomer: /^Företag$|^Foretag$/i,
    individualCustomer: /Privatperson|Privat kund|Individuell kund/i,
    firstName: /^Förnamn|^Fornamn/i,
    lastName: /^Efternamn/i,
    email: /E-post|Epost|Email/i,
    phone: /Telefon|Mobiltelefon/i,
    terms: /Användarvillkoren|Anvandarvillkoren|villkor/i,
    privacy: /Integritetspolicyn|Integritetspolicy|sekretesspolicy/i,
    loadingInfo: /Vi kontrollerar dina uppgifter|Vänta lite/i,
    viesSuccess: /momsnummer.*bekräftat|momsnummer.*bekraftat|VAT.*bekräftat|VAT.*bekraftat/i,
  },
  placeholders: {
    firstName: /^förnamn|^fornamn/i,
    lastName: /^efternamn/i,
    company: /företag|foretag|företagsnamn|foretagsnamn/i,
    taxId: /moms|vat|organisationsnummer/i,
    address1: /^ange adress$|^adress\*?$|^adress$/i,
    address2: /adresskomplement|adressrad 2|kompletterande adress|lägenhet|lagenhet/i,
    postcode: /postnummer/i,
    city: /ort|stad/i,
  },
  placeholderHints: {
    address: 'adress',
    postcode: 'post',
  },
  pricePatterns: {
    subtotal: /Delsumma\s*([\d\s.,]+)\s*(?:kr|SEK|€|EUR)?/i,
    shipping: /Leverans\s*([\d\s.,]+)\s*(?:kr|SEK|€|EUR)?/i,
    tax: /(?:Inklusive moms|Moms|VAT)\s*([\d\s.,]+)\s*(?:kr|SEK|€|EUR)?/i,
    total: /Totalt:?\s*([\d\s.,]+)\s*(?:kr|SEK|€|EUR)?/i,
  },
  summaryPatterns: {
    total: /Totalt|Leveransmetod|Leverans/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Stäng"]',
      'button.close-dialog-icon[aria-label="Stang"]',
      'button[aria-label="Stäng"]',
      'button[aria-label="Stang"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Stäng"]',
      'button[title="Stang"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|nyhetsbrev|prenumerera/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Stäng"], #newsletter_popup button[aria-label="Stang"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /stäng|stang|close|senare|skip/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-SE-to-PT',
      description: 'privatkund i EU behåller delsumman oförändrad',
      billingCountry: 'Portugal',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Rua do Comercio 123',
        address2: '',
        postcode: '1100-150',
        city: 'Lissabon',
        phone: '123456789',
      },
    },
    {
      key: 'company-SE-to-PT-no-vies',
      description: 'företag med korrekt momsnummerformat men utan VIES-träff behåller delsumman oförändrad',
      billingCountry: 'Portugal',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Testföretag utan VIES',
        taxId: '500100145',
        address1: 'Rua do Comercio 123',
        address2: '',
        postcode: '1100-150',
        city: 'Lissabon',
        phone: '123456789',
      },
    },
    {
      key: 'SE-to-FR',
      description: 'företag med giltigt VIES-nummer i annat EU-land tar bort moms',
      billingCountry: 'Frankrike',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Testföretag VIES FR',
        taxId: '59542051180',
        address1: '10 Rue de la Paix',
        address2: '',
        postcode: '75002',
        city: 'Paris',
        phone: '123456789',
      },
    },
  ],
};
