export const skMarket = {
  key: 'SK',
  baseUrl: 'https://vasco-electronics.sk/',
  checkoutPath: 'objednavka',
  product: {
    name: 'Vasco Translator Q1',
    path: '/prekladace/vasco-translator-q1',
  },
  labels: {
    cart: /Košík|Nákupný košík/i,
    addToCart: /Pridať do košíka/i,
    continue: /Pokračovať/i,
    summary: /Zhrnutie|Súhrn objednávky|Spolu/i,
    personalInfoStep: /Osobné údaje|Osobné informácie/i,
    addressesStep: /Adresy|Adresa/i,
    shippingStep: /Spôsob doručenia|Doručenie/i,
    paymentReady: /Ako by ste chceli platiť\?|Vykonať platbu/i,
    companyCustomer: /^Spoločnosť$|^Firma$/i,
    individualCustomer: /^Jednotlivec$|Súkromná osoba|Individuálny zákazník|Súkromný zákazník/i,
    firstName: /^Krstné meno|^Meno/i,
    lastName: /^Priezvisko/i,
    email: /E-mail/i,
    phone: /Telefón/i,
    terms: /Prečítal som si a súhlasím so zmluvnými podmienkami|zmluvnými podmienkami|obchodné podmienky/i,
    privacy: /Prečítal som si a akceptujem Zásady ochrany osobných údajov|Zásady ochrany osobných údajov|ochrana osobných údajov/i,
    loadingInfo: /Čakajte prosím.*Kontrolujeme vaše údaje|Kontrolujeme vaše údaje/i,
    viesSuccess:
      /IČ DPH.*úspešne overené|IČ DPH.*overené|DPH.*overené|aktívne v systéme VIES|cena zníži o DPH|Faktúra bude vystavená s DPH 0%/i,
  },
  placeholders: {
    firstName: /meno|krstné meno/i,
    lastName: /priezvisko/i,
    company: /firma|spoločnosť/i,
    taxId: /ič dph|dph|vat|daň/i,
    address1: /^zadajte ulica$|^ulica$/i,
    address2: /^zadajte číslo domu$|číslo domu|číslo popisné/i,
    postcode: /^zadajte psč$|^psč$|poštové smerovacie číslo/i,
    city: /^zadajte mesto$|^mesto$|obec/i,
  },
  placeholderHints: {
    address: 'adres',
    postcode: 'psč',
  },
  pricePatterns: {
    subtotal: /Medzisúčet\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    shipping: /Doručenie\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    tax: /(?:DPH|vrátane DPH)\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
    total: /Spolu\s*([\d\s.,]+)\s*(?:€|EUR)?/i,
  },
  summaryPatterns: {
    total: /Spolu|Spôsob doručenia|Doručenie/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Zavrieť"]',
      'button[aria-label="Zavrieť"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button[title="Zavrieť"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|novinky|odber|prihlás/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Zavrieť"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /zavrieť|close|neskôr|skip/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-SK-to-DE',
      description: 'súkromný zákazník v EÚ ponechá medzisúčet bez zmeny',
      billingCountry: 'Nemecko',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Friedrichstrasse',
        address2: '123',
        postcode: '10117',
        city: 'Berlin',
        phone: '123456789',
      },
    },
    {
      key: 'company-SK-to-DE-no-vies',
      description: 'firma so správnym formátom IČ DPH, ale bez záznamu vo VIES ponechá medzisúčet bez zmeny',
      billingCountry: 'Nemecko',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Test firma bez VIES',
        taxId: '129273399',
        address1: 'Friedrichstrasse',
        address2: '123',
        postcode: '10117',
        city: 'Berlin',
        phone: '123456789',
      },
    },
    {
      key: 'SK-to-DE',
      description: 'firma s platným VIES číslom v inej krajine EÚ odstráni DPH',
      billingCountry: 'Nemecko',
      customerType: 'company',
      expectedTotalChange: 'decrease',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Test firma VIES DE',
        taxId: '129273398',
        address1: 'Friedrichstrasse',
        address2: '123',
        postcode: '10117',
        city: 'Berlin',
        phone: '123456789',
      },
    },
  ],
};
