export const ukMarket = {
  key: 'UK',
  baseUrl: 'https://vasco-electronics.co.uk/',
  checkoutPath: 'order',
  product: {
    name: 'Vasco Translator Q1',
    path: '/translator/vasco-translator-q1',
  },
  labels: {
    cart: /Cart|Basket/i,
    addToCart: /Add to basket|Add to cart/i,
    continue: /Continue/i,
    summary: /Summary|Order summary/i,
    personalInfoStep: /Personal information|Your information/i,
    addressesStep: /Addresses|Address/i,
    shippingStep: /Shipping method|Delivery method|Shipping/i,
    companyCustomer: /^Company$/i,
    individualCustomer: /Individual|Private customer|Personal customer/i,
    firstName: /^First name/i,
    lastName: /^Last name|^Name/i,
    email: /E-mail|Email/i,
    phone: /Phone|Telephone/i,
    terms: /Terms of Service|Terms and Conditions|terms and conditions/i,
    privacy: /Privacy Policy|privacy/i,
    loadingInfo: /We are verifying your data|Checking your data|Verifying your data/i,
    viesSuccess: /VAT number .* verified|VAT .* verified|successfully verified/i,
  },
  placeholders: {
    firstName: /first name/i,
    lastName: /last name|name/i,
    company: /company|business/i,
    taxId: /vat|tax|number/i,
    address1: /^enter address$|^address$/i,
    address2: /address 2|apartment|unit|suite/i,
    postcode: /postal code|postcode|zip/i,
    city: /city|town/i,
  },
  placeholderHints: {
    address: 'address',
    postcode: 'post',
  },
  pricePatterns: {
    subtotal: /Subtotal\s*(?:£|GBP|€|EUR)?\s*([\d\s.,]+)/i,
    shipping: /Shipping\s*(?:£|GBP|€|EUR)?\s*([\d\s.,]+)/i,
    tax: /VAT(?:\s*\(included\))?\s*(?:£|GBP|€|EUR)?\s*([\d\s.,]+)/i,
    total: /Total\s*:?\s*(?:£|GBP|€|EUR)?\s*([\d\s.,]+)/i,
  },
  summaryPatterns: {
    total: /Total|Shipping method|Shipping/i,
  },
  cookieSelectors: {
    primaryButtons: [
      '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
      '#CybotCookiebotDialogBodyLevelButtonAccept',
      '#CybotCookiebotDialogBodyButtonAccept',
      '#CybotCookiebotDialogBodyLevelButtonCustomize',
    ],
  },
  popupSelectors: {
    popupContainers: [
      'dialog#discount-popup',
      'dialog[open]',
      '[role="dialog"]',
      '.modal.show',
      '.popup.show',
      '#newsletter_popup',
      '.newsletter-popup',
      '.newsletter-modal',
      '[id*="newsletter" i]',
      '[class*="newsletter" i]',
    ],
    closeButtons: [
      'button.close-dialog-icon[aria-label="Close"]',
      'button[aria-label="Close"]',
      'button[title="Close"]',
      'button.close-modal',
      'button.close',
      'button[class*="close" i]',
      '.mfp-close',
      '.modal-close',
      '.newsletter-close',
      '[class*="close" i]',
      '[data-dismiss="modal"]',
    ],
    newsletterText: /newsletter|sign up|subscribe/i,
    genericCloseTargets: [
      page => page.locator('#newsletter_popup .close, #newsletter_popup button[aria-label="Close"]').first(),
      page => page.locator('.newsletter-popup .close, .newsletter-popup .mfp-close, .newsletter-popup button').first(),
      page => page.locator('[id*="newsletter" i] button[class*="close" i], [class*="newsletter" i] button[class*="close" i]').first(),
      page => page.getByRole('button', { name: /close|later|skip|no thanks/i }).first(),
    ],
  },
  scenarios: [
    {
      key: 'individual-UK-to-PT',
      description: 'individual customer in the EU keeps subtotal unchanged',
      billingCountry: 'Portugal',
      customerType: 'individual',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: '',
        taxId: '',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisbon',
        phone: '123456789',
      },
    },
    {
      key: 'company-UK-to-PT-no-vies',
      description: 'company with valid VAT format but no VIES entry keeps subtotal unchanged',
      billingCountry: 'Portugal',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Test company without VIES',
        taxId: '500100145',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisbon',
        phone: '123456789',
      },
    },
    {
      key: 'company-UK-to-PT-vies-no-change',
      description: 'company with valid VIES number in another EU country still keeps subtotal unchanged on the UK market',
      billingCountry: 'Portugal',
      customerType: 'company',
      expectedTotalChange: 'same',
      business: {
        firstName: 'Automat',
        lastName: 'Test',
        email: 'testcases.web@gmail.com',
        company: 'Test company VIES PT',
        taxId: '500100144',
        address1: 'Rua do Comercio 128',
        address2: '',
        postcode: '1100-150',
        city: 'Lisbon',
        phone: '123456789',
      },
    },
  ],
};
