import { test, expect } from '../helpers/free-shipping-test.js';
test.setTimeout(120000);
const fr = { base: 'https://vasco-electronics.fr/', products: '/traducteur-electronique/', checkout: '/commande', paid: 9, q1: '38', glass: '40', customer: { first: 'Automat', last: 'Test', address: '12 Rue de Rivoli', postcode: '75001', city: 'Paris', phone: '0612345678' } };
for (const scenario of [{ name: 'poniżej progu', product: fr.glass, free: false }, { name: 'powyżej progu', product: fr.q1, free: true }]) test(`FR: darmowa dostawa ${scenario.name}`, async ({ page }) => {
  await page.goto(new URL(fr.products, fr.base).href, { waitUntil: 'domcontentloaded' }); await cookies(page);
  const card = page.locator(`article.product-miniature[data-id-product="${scenario.product}"]`); await expect(card).toBeVisible({ timeout: 15000 }); await card.locator('button.add-to-cart').click(); await expect(page.locator('#header .cart-count').first()).toHaveText('1', { timeout: 15000 });
  await page.goto(new URL(fr.checkout, fr.base).href, { waitUntil: 'domcontentloaded' }); await cookies(page);
  await fill(page, /^Prénom|^Prenom/i, fr.customer.first); await fill(page, /^Nom/i, fr.customer.last); await fill(page, /E-mail|Email/i, `testcases.web+free-shipping-fr-${Date.now().toString(36)}@gmail.com`);
  for (const label of [/Conditions générales|Conditions d'utilisation/i, /Politique de confidentialité/i]) { const box = page.getByRole('checkbox', { name: label }).first(); await expect(box).toBeVisible({ timeout: 15000 }); await box.check({ force: true }).catch(async () => box.evaluate(input => input.click())); await expect(box).toBeChecked(); }
  await openAddress(page); await fillLast(page, /prénom|prenom/i, fr.customer.first); await fillLast(page, /nom/i, fr.customer.last); await fillLast(page, /^Adresse/i, fr.customer.address); await fillLast(page, /code postal/i, fr.customer.postcode); await fillLast(page, /^Ville/i, fr.customer.city); await fillLast(page, /téléphone|telephone/i, fr.customer.phone); await next(page, -1);
  await expect.poll(async () => /Choisissez votre mode de livraison/i.test(await page.locator('body').innerText()), { timeout: 30000 }).toBeTruthy();
  const prices = await readPrices(page); expect(prices.length).toBeGreaterThan(0); if (scenario.free) expect(prices).toContain(0); else expect(prices).toContain(fr.paid);
});
async function cookies(page) { const dialog = page.locator('#CybotCookiebotDialog'); await dialog.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {}); const button = page.locator('#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll, #CybotCookiebotDialogBodyLevelButtonAccept, #CybotCookiebotDialogBodyButtonAccept').first(); if (await button.isVisible().catch(() => false)) await button.click({ force: true }); }
async function addressReady(page) { return await page.getByRole('textbox', { name: /adresse/i }).last().isVisible().catch(() => false); }
async function openAddress(page) { if (await addressReady(page)) return; const button = page.locator('button[name="continue"]').first(); await expect(button).toBeVisible({ timeout: 15000 }); await button.click({ force: true }); await expect.poll(() => addressReady(page), { timeout: 10000 }).toBeTruthy().catch(() => {}); if (await addressReady(page)) return; await page.goto(new URL('/commande?id_address=0', fr.base).href, { waitUntil: 'domcontentloaded' }); const tab = page.getByText(/^Adresses$/i).first(); if (await tab.isVisible().catch(() => false)) await tab.click({ force: true }); await expect.poll(() => addressReady(page), { timeout: 20000 }).toBeTruthy(); }
async function fill(page, pattern, value) { const field = page.getByRole('textbox', { name: pattern }).first(); await expect(field).toBeVisible({ timeout: 15000 }); await field.fill(value); }
async function fillLast(page, pattern, value) { for (const field of [page.getByPlaceholder(pattern).last(), page.getByRole('textbox', { name: pattern }).last()]) if (await field.isVisible().catch(() => false)) { await field.fill(value); return; } throw new Error(`FR field not found: ${pattern}`); }
async function next(page, index) { const buttons = page.getByRole('button', { name: /Continuer|Poursuivre/i }); const button = index < 0 ? buttons.last() : buttons.nth(index); await expect(button).toBeVisible({ timeout: 15000 }); await button.click({ force: true }); }
async function readPrices(page) { return await page.getByText(/^Choisissez votre mode de livraison$/i).locator('xpath=..').locator('p').evaluateAll(nodes => nodes.map(node => node.textContent?.trim() || '').map(text => { const match = text.match(/(?:€|EUR)\s*([\d.,]+)|([\d.,]+)\s*(?:€|EUR)/i); return /gratuit|free/i.test(text) ? 0 : match ? Number((match[1] || match[2]).replace(',', '.')) : null; }).filter(price => price !== null)); }
