import { test, expect } from '../helpers/free-shipping-test.js';
import { readShippingSummary, shippingPriceFromText } from '../helpers/shipping-methods.js';
test.setTimeout(120000);
const pt={base:'https://vasco-translator.pt/',products:'/todos-produtos/',checkout:'/encomenda',paid:9,q1:'38',glass:'40'};
for(const s of [{name:'poniżej progu',product:pt.glass,free:false},{name:'powyżej progu',product:pt.q1,free:true}])test(`PT: darmowa dostawa ${s.name}`,async({page})=>{
 await page.goto(new URL(pt.products,pt.base).href,{waitUntil:'domcontentloaded'});await cookies(page);const card=page.locator(`article.product-miniature[data-id-product="${s.product}"]`);await expect(card).toBeVisible({timeout:15000});const add=card.locator('button.add-to-cart');await add.click({force:true});await expect.poll(async()=>Number((await page.locator('#header .cart-count').first().innerText()).trim()),{timeout:5000}).toBe(1).catch(async()=>add.evaluate(element=>element.click()));await expect(page.locator('#header .cart-count').first()).toHaveText('1',{timeout:15000});
 await page.goto(new URL(pt.checkout,pt.base).href,{waitUntil:'domcontentloaded'});await cookies(page);await page.locator('input[name="firstname"]').fill('Automat');await page.locator('input[name="lastname"]').fill('Test');await page.locator('input[name="email"]').fill(`testcases.web+free-shipping-pt-${Date.now().toString(36)}@gmail.com`);
 for(const n of [/Termos de Serviço|Termos e condições|Termos e condicoes|condições|condicoes/i,/Política de Privacidade|Politica de Privacidade|privacidade/i]){const b=page.getByRole('checkbox',{name:n}).first();await expect(b).toBeVisible({timeout:15000});await b.check({force:true}).catch(async()=>b.evaluate(e=>e.click()));}
 const next=page.getByRole('button',{name:/Continuar/i});const ready=async()=>await page.getByPlaceholder(/morada|endereço|endereco|rua/i).first().isVisible().catch(()=>false);const b=page.locator('button[name="continue"][data-link-action="register-new-customer"]').first();await b.click({force:true}).catch(async()=>next.first().click({force:true}));await expect.poll(ready,{timeout:30000}).toBeTruthy();
 const fill=async(n,v)=>{for(const f of [page.getByPlaceholder(n).last(),page.getByRole('textbox',{name:n}).last()])if(await f.isVisible().catch(()=>false)){await f.fill(v);return;}throw Error(`PT ${n}`)};await fill(/nome/i,'Automat');await fill(/apelido|sobrenome/i,'Test');await fill(/morada|endereço|endereco|rua/i,'Rua do Comercio 128');await fill(/código postal|codigo postal/i,'1100-150');await fill(/cidade/i,'Lisboa');await fill(/telefone/i,'912345678');await next.last().click({force:true});await expect.poll(async()=>/método de envio|metodo de envio|método de entrega|metodo de entrega/i.test(await page.locator('body').innerText()),{timeout:30000}).toBeTruthy();
 const shipping=await readShippingSummary(page,/^Envio$/i);expect(shipping,'PT shipping summary').not.toBeNull();const price=shippingPriceFromText(shipping,{currency:/€|EUR/,freePattern:/grátis|gratis|free/i});expect(price).not.toBeNull();if(s.free)expect(price).toBe(0);else expect(price).toBe(pt.paid);
});
async function cookies(page){const d=page.locator('#CybotCookiebotDialog');await d.waitFor({state:'visible',timeout:5000}).catch(()=>{});const b=page.locator('#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll,#CybotCookiebotDialogBodyLevelButtonAccept').first();if(await b.isVisible().catch(()=>false))await b.click({force:true})}
