import { test, expect } from '../helpers/free-shipping-test.js';
test.setTimeout(120000);
const nl = { base: 'https://vasco-electronics.nl/', products: '/alle-producten/', checkout: '/bestelling', paid: 9, q1: '38', glass: '40', customer: { first: 'Automat', last: 'Test', address: 'Damrak 12', postcode: '1012 LG', city: 'Amsterdam', phone: '612345678' } };
for (const scenario of [{ name: 'poniżej progu', product: nl.glass, free: false }, { name: 'powyżej progu', product: nl.q1, free: true }]) test(`NL: darmowa dostawa ${scenario.name}`, async ({ page }) => {
  await page.goto(new URL(nl.products, nl.base).href, { waitUntil: 'domcontentloaded' }); await cookies(page); const card = page.locator(`article.product-miniature[data-id-product="${scenario.product}"]`); await expect(card).toBeVisible({ timeout: 15000 }); await card.locator('button.add-to-cart').click(); await expect(page.locator('#header .cart-count').first()).toHaveText('1', { timeout: 15000 });
  await page.goto(new URL(nl.checkout, nl.base).href, { waitUntil: 'domcontentloaded' }); await cookies(page); await fill(page, /^Voornaam/i, nl.customer.first); await fill(page, /^Achternaam|^Naam/i, nl.customer.last); await fill(page, /E-mail|Email/i, `testcases.web+free-shipping-nl-${Date.now().toString(36)}@gmail.com`);
  for (const label of [/Servicevoorwaarden|algemene voorwaarden/i, /Privacybeleid|privacyverklaring|privacy/i]) { const box = page.getByRole('checkbox', { name: label }).first(); await expect(box).toBeVisible({ timeout: 15000 }); await box.check({ force: true }).catch(async () => box.evaluate(input => input.click())); await expect(box).toBeChecked(); }
  await openAddress(page); await last(page, /voornaam/i, nl.customer.first); await last(page, /achternaam|naam/i, nl.customer.last); await last(page, /^Adres\*/i, nl.customer.address); await last(page, /postcode/i, nl.customer.postcode); await last(page, /plaats|stad/i, nl.customer.city); await last(page, /telefoon|phone/i, nl.customer.phone); await next(page, -1);
  await expect.poll(async () => /Kies uw bezorgmethode|Bezorgmethode|Verzendmethode|Verzendingswijze/i.test(await page.locator('body').innerText()), { timeout: 30000 }).toBeTruthy();
  await expect.poll(async () => (await pricesOf(page)).length, { timeout: 60000 }).toBeGreaterThan(0);
  const prices = await pricesOf(page); if (scenario.free) expect(prices).toContain(0); else expect(prices).toContain(nl.paid);
});
async function cookies(page) { const d = page.locator('#CybotCookiebotDialog'); await d.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {}); const b = page.locator('#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll, #CybotCookiebotDialogBodyLevelButtonAccept, #CybotCookiebotDialogBodyButtonAccept').first(); if (await b.isVisible().catch(() => false)) await b.click({ force: true }); }
async function ready(page) { return await page.getByRole('textbox', { name: /adres/i }).last().isVisible().catch(() => false); }
async function openAddress(page) { if (await ready(page)) return; const b = page.locator('button[name="continue"]').first(); await expect(b).toBeVisible({ timeout: 15000 }); await b.click({ force: true }); await expect.poll(() => ready(page), { timeout: 10000 }).toBeTruthy().catch(() => {}); if (await ready(page)) return; await page.goto(new URL('/bestelling?id_address=0', nl.base).href, { waitUntil: 'domcontentloaded' }); const tab = page.getByText(/^Adressen$|^Adres$/i).first(); if (await tab.isVisible().catch(() => false)) await tab.click({ force: true }); await expect.poll(() => ready(page), { timeout: 20000 }).toBeTruthy(); }
async function fill(page, n, v) { const f = page.getByRole('textbox', { name: n }).first(); await expect(f).toBeVisible({ timeout: 15000 }); await f.fill(v); }
async function last(page, n, v) { for (const f of [page.getByPlaceholder(n).last(), page.getByRole('textbox', { name: n }).last()]) if (await f.isVisible().catch(() => false)) { await f.fill(v); return; } throw new Error(`NL field not found: ${n}`); }
async function next(page, i) { const b = page.getByRole('button', { name: /Verder|Doorgaan/i }); const f = i < 0 ? b.last() : b.nth(i); await expect(f).toBeVisible({ timeout: 15000 }); await f.click({ force: true }); }
async function pricesOf(page) { try { return await page.getByText(/^Kies uw (?:bezorgmethode|leveringswijze)$/i).locator('xpath=..').locator('p').evaluateAll(nodes => nodes.map(n => n.textContent?.trim() || '').map(t => { const m = t.match(/(?:€|EUR)\s*([\d.,]+)|([\d.,]+)\s*(?:€|EUR)/i); return /gratis|free/i.test(t) ? 0 : m ? Number((m[1] || m[2]).replace(',', '.')) : null; }).filter(p => p !== null)); } catch { return []; } }
