import { test, expect } from '../helpers/free-shipping-test.js';
import { readShippingSummary, shippingPriceFromText } from '../helpers/shipping-methods.js';
test.setTimeout(120000);
const dk={base:'https://vasco-translator.dk/',products:'/alle-produkter/',checkout:'/ordre',q1:'38',glass:'40'};
for(const s of [{name:'niska wartość',product:dk.glass},{name:'wyższa wartość',product:dk.q1}])test(`DK: darmowa dostawa — ${s.name}`,async({page})=>{
 await page.goto(new URL(dk.products,dk.base).href,{waitUntil:'domcontentloaded'});await cookies(page);const card=page.locator(`article.product-miniature[data-id-product="${s.product}"]`);await expect(card).toBeVisible({timeout:15000});const add=card.locator('button.add-to-cart');await add.click({force:true});await expect.poll(async()=>Number((await page.locator('#header .cart-count').first().innerText()).trim()),{timeout:5000}).toBe(1).catch(async()=>add.evaluate(e=>e.click()));await expect(page.locator('#header .cart-count').first()).toHaveText('1',{timeout:15000});
 await page.goto(new URL(dk.checkout,dk.base).href,{waitUntil:'domcontentloaded'});await cookies(page);await page.locator('input[name="firstname"]').fill('Automat');await page.locator('input[name="lastname"]').fill('Test');await page.locator('input[name="email"]').fill(`testcases.web+free-shipping-dk-${Date.now().toString(36)}@gmail.com`);
 for(const n of [/servicevilkar|servicevilkår|betingelser/i,/privatlivspolitik|persondatapolitik/i]){const b=page.getByRole('checkbox',{name:n}).first();await expect(b).toBeVisible({timeout:15000});await b.check({force:true}).catch(async()=>b.evaluate(e=>e.click()));}
 const cont=page.getByRole('button',{name:/Fortsæt|Fortsat/i});const ready=async()=>await page.getByPlaceholder(/^indtast adresse$|^adresse$/i).first().isVisible().catch(()=>false);const b=page.locator('button[name="continue"][data-link-action="register-new-customer"]').first();await b.click({force:true}).catch(async()=>cont.first().click({force:true}));await expect.poll(ready,{timeout:10000}).toBeTruthy().catch(async()=>{await b.evaluate(e=>e.click()).catch(()=>{})});await expect.poll(ready,{timeout:20000}).toBeTruthy();
 const fill=async(n,v)=>{for(const f of [page.getByPlaceholder(n).last(),page.getByRole('textbox',{name:n}).last()])if(await f.isVisible().catch(()=>false)){await f.fill(v);return;}throw Error(`DK ${n}`)};await fill(/fornavn/i,'Automat');await fill(/efternavn|navn/i,'Test');await fill(/adresse|gade/i,'Norre Voldgade 123');await fill(/postnummer/i,'1358');await fill(/by/i,'Kobenhavn');await fill(/telefon/i,'888123456');await cont.last().click({force:true});await expect.poll(async()=>/leveringsmetode|levering/i.test(await page.locator('body').innerText()),{timeout:30000}).toBeTruthy();
 const shipping=await readShippingSummary(page,/^Levering$/i);expect(shipping,'DK shipping summary').not.toBeNull();expect(shippingPriceFromText(shipping,{currency:/kr\.?|DKK/,freePattern:/gratis|free/i})).toBe(0);
});
async function cookies(page){const d=page.locator('#CybotCookiebotDialog');await d.waitFor({state:'visible',timeout:5000}).catch(()=>{});const b=page.locator('#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll,#CybotCookiebotDialogBodyLevelButtonAccept').first();if(await b.isVisible().catch(()=>false))await b.click({force:true})}
