export const cartMarkets = [
  {
    code: 'PL',
    baseUrl: 'https://vasco-electronics.pl/',
    allProductsPath: '/wszystkie/',
    cartPath: '/koszyk?action=show',
    cartLabelPattern: /Koszyk/i,
    allProductsPattern: /Wszystkie produkty/i,
    menuPattern: /sklep/i,
  },
  {
    code: 'BG',
    baseUrl: 'https://vasco-electronics.bg/',
    allProductsPath: '/vsicki-produkti/',
    cartPath: '/kolicka?action=show',
    cartLabelPattern: /Количка/i,
    allProductsPattern: /Всички продукти/i,
    menuPattern: /магазин/i,
  },
  {
    code: 'DK',
    baseUrl: 'https://vasco-translator.dk/',
    allProductsPath: '/alle-produkter/',
    cartPath: '/kurv?action=show',
    cartLabelPattern: /Kurv/i,
    allProductsPattern: /Alle produkter/i,
    menuPattern: /shop|produkter|translator/i,
  },
  {
    code: 'UK',
    baseUrl: 'https://vasco-electronics.co.uk/',
    allProductsPath: '/all-products/',
    cartPath: '/cart?action=show',
    cartLabelPattern: /Cart/i,
    allProductsPattern: /All products/i,
    menuPattern: /shop|translators|products/i,
  },
  {
    code: 'COM',
    baseUrl: 'https://vasco-translator.com/',
    allProductsPath: '/all-products/',
    cartPath: '/cart?action=show',
    cartLabelPattern: /Cart/i,
    allProductsPattern: /All products/i,
    menuPattern: /shop|translator|translators|products/i,
  },
  {
    code: 'ES',
    baseUrl: 'https://traductor-de-voz.es/',
    allProductsPath: '/productos/',
    cartPath: '/carrito?action=show',
    cartLabelPattern: /Carrito/i,
    allProductsPattern: /Productos/i,
    menuPattern: /tienda|traductor|productos/i,
  },
  {
    code: 'BE FR',
    baseUrl: 'https://vasco-translator.be/fr/',
    allProductsPath: '/fr/tous-les-produits/',
    cartPath: '/fr/panier?action=show',
    cartLabelPattern: /Panier/i,
    allProductsPattern: /Tous les produits/i,
    menuPattern: /boutique|traducteurs|produits/i,
  },
  {
    code: 'BE NL',
    baseUrl: 'https://vasco-translator.be/nl/',
    allProductsPath: '/nl/alle-producten/',
    cartPath: '/nl/winkelwagen?action=show',
    cartLabelPattern: /Winkelwagen/i,
    allProductsPattern: /Alle producten/i,
    menuPattern: /winkel|vertalers|producten/i,
  },
  {
    code: 'HR',
    baseUrl: 'https://vasco-translator.hr/',
    allProductsPath: '/proizvodi/',
    cartPath: '/kosarica?action=show',
    cartLabelPattern: /Košarica|Kosarica/i,
    allProductsPattern: /Proizvodi/i,
    menuPattern: /trgovina|prevoditelj|proizvodi/i,
  },
  {
    code: 'IT',
    baseUrl: 'https://vasco-electronics.it/',
    allProductsPath: '/tutti-i-prodotti/',
    cartPath: '/carrello?action=show',
    cartLabelPattern: /Carrello/i,
    allProductsPattern: /Tutti i prodotti/i,
    menuPattern: /negozio|traduttori|prodotti/i,
  },
  {
    code: 'LT',
    baseUrl: 'https://vasco-translator.lt/',
    allProductsPath: '/visi-produktai/',
    cartPath: '/krepselis?action=show',
    cartLabelPattern: /Krepšelis|Krepselis/i,
    allProductsPattern: /Visi produktai/i,
    menuPattern: /parduotuve|vertej|produktai/i,
  },
  {
    code: 'RO',
    baseUrl: 'https://vasco-electronics.ro/',
    allProductsPath: '/toate-produsele/',
    cartPath: '/cos?action=show',
    cartLabelPattern: /Coș|Cos/i,
    allProductsPattern: /Toate produsele/i,
    menuPattern: /magazin|translator|produse/i,
  },
  {
    code: 'SE',
    baseUrl: 'https://vasco-translator.se/',
    allProductsPath: '/alla-produkter/',
    cartPath: '/varukorg?action=show',
    cartLabelPattern: /Varukorg/i,
    allProductsPattern: /Alla produkter/i,
    menuPattern: /butik|översättare|oversattare|produkter/i,
  },
  {
    code: 'CZ',
    baseUrl: 'https://vasco-electronics.cz/',
    allProductsPath: '/vsechny-vyrobky/',
    cartPath: '/kosik?action=show',
    cartLabelPattern: /Košík|Kosik/i,
    allProductsPattern: /Všechny výrobky|Vsechny vyrobky/i,
    menuPattern: /obchod|překladače|prekladace|výrobky|vyrobky/i,
  },
  {
    code: 'DE',
    baseUrl: 'https://vasco-electronics.de/',
    allProductsPath: '/alle-produkte/',
    cartPath: '/warenkorb?action=show',
    cartLabelPattern: /Warenkorb/i,
    allProductsPattern: /Alle Produkte/i,
    menuPattern: /shop|übersetzer|ubersetzer|produkte/i,
  },
  {
    code: 'FI',
    baseUrl: 'https://vasco-translator.fi/',
    allProductsPath: '/kaikki-tuotteet/',
    cartPath: '/ostoskori?action=show',
    cartLabelPattern: /Ostoskori/i,
    allProductsPattern: /Kaikki tuotteet/i,
    menuPattern: /kauppa|shop|kääntäjät|kaantajat|tuotteet/i,
  },
  {
    code: 'FR',
    baseUrl: 'https://vasco-electronics.fr/',
    allProductsPath: '/traducteur-electronique/',
    cartPath: '/panier?action=show',
    cartLabelPattern: /Panier/i,
    allProductsPattern: /Tous les produits/i,
    menuPattern: /boutique|traducteurs|produits|shop/i,
  },
  {
    code: 'HU',
    baseUrl: 'https://vasco-electronics.hu/',
    allProductsPath: '/minden-termek/',
    cartPath: '/cart?action=show',
    cartLabelPattern: /Kosár|Kosar/i,
    allProductsPattern: /Minden termék|Osszes termek|Összes termék/i,
    menuPattern: /bolt|shop|fordít|fordit|termék|termek/i,
  },
  {
    code: 'NL',
    baseUrl: 'https://vasco-electronics.nl/',
    allProductsPath: '/alle-producten/',
    cartPath: '/winkelmandje?action=show',
    cartLabelPattern: /Winkelwagen|Winkelmandje/i,
    allProductsPattern: /Alle producten/i,
    menuPattern: /winkel|shop|vertaler|vertalers|producten/i,
  },
  {
    code: 'SK',
    baseUrl: 'https://vasco-electronics.sk/',
    allProductsPath: '/vsetky-produkty/',
    cartPath: '/nakupny-kosik?action=show',
    cartLabelPattern: /Košík|Kosik/i,
    allProductsPattern: /Všetky produkty|Vsetky produkty/i,
    menuPattern: /obchod|preklad|produkty/i,
  },
  {
    code: 'PT',
    baseUrl: 'https://vasco-translator.pt/',
    allProductsPath: '/todos-produtos/',
    cartPath: '/carrinho?action=show',
    cartLabelPattern: /Carrinho/i,
    allProductsPattern: /Todos os produtos/i,
    menuPattern: /loja|shop|tradutor|tradutores|produtos/i,
  },
];

export const cartMarketsByCode = Object.fromEntries(cartMarkets.map(market => [market.code, market]));
